
DROP TABLE IF EXISTS `T_G16`;

CREATE TABLE `T_G16` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增长主键',
  `CREATE_ID` bigint(20) NOT NULL COMMENT 'create schedule id',
  `DELETE_ID` bigint(20) NOT NULL DEFAULT '0' COMMENT '删除记录的Schedule ID',
  `AREACD` char(3) NOT NULL COMMENT 'ATPCO Area Codes.',
  `TYPE` char(1) DEFAULT NULL COMMENT 'Indicator to identify the type of tariff\r\n            record.',
  `CXR` char(2) NOT NULL COMMENT 'A standard industry carrier code as\r\n            defined in the IATA Airline Coding Directory.',
  `FILLER` varchar(8) DEFAULT NULL,
  `EFFDATE` datetime DEFAULT NULL COMMENT 'YYMMDD Format',
  `DISDATE` datetime NOT NULL COMMENT 'YYMMDD Format',
  `STAMP` datetime DEFAULT NULL COMMENT 'The datetime on which the record\r\n            was created.',
  `PRIVATE_TAG` char(1) DEFAULT NULL COMMENT 'Private Tariff Designator to identify\r\n            Fare, Add-on (Arbitrary), Zone, Fare Class, Fare\r\n            Rule, Footnote and Unpublished Tariffs are\r\n            private.',
  `FILLER1` varchar(8) DEFAULT NULL COMMENT 'Filler',
  `PAPERTARIFF` varchar(8) DEFAULT NULL COMMENT 'ATPCO Paper Tariff Code.',
  `NTANUM` varchar(3) DEFAULT NULL COMMENT 'ATPCO NTA Number for the Paper Tariff coded.',
  `DOTNUM` varchar(3) DEFAULT NULL COMMENT 'ATPCO DOT Number for the Paper Tariff coded.',
  `FCAST` char(1) DEFAULT NULL COMMENT 'Symbol that precedes Fare Class Tariff\r\n            Code to indicate that the tariff coded is not\r\n            contained within PAPER TARIFF (in LOC 56-62)\r\n            but is coded to establish cross relationships\r\n            between tariffs.',
  `FCTARIFFCD` varchar(8) DEFAULT NULL COMMENT 'ATPCO Fare Class Tariff Code.',
  `FCTARIFFNUM` varchar(3) DEFAULT NULL COMMENT 'Corresponding ATPCO Tariff Number.',
  `FRAST` char(1) DEFAULT NULL COMMENT 'Symbol that precedes Fare Rule Tariff\r\n            Code to indicate that the tariff coded is not\r\n            contained within PAPER TARIFF (in LOC 56-\r\n            62) but is coded to establish cross\r\n            relationships between tariffs.',
  `FRTARIFFCD` varchar(8) DEFAULT NULL COMMENT 'ATPCO Fare Rule Tariff Code.',
  `FRTARIFFNUM` varchar(3) DEFAULT NULL COMMENT 'Corresponding ATPCO Tariff Number.',
  `GRAST` char(1) DEFAULT NULL COMMENT 'Symbol that precedes Governing Rule\r\n            Tariff Code to indicate that the tariff coded is\r\n            not contained within PAPER TARIFF (in LOC\r\n            56-62) but is coded to establish cross\r\n            relationships between tariffs.',
  `GRTARIFFCD` varchar(8) DEFAULT NULL COMMENT 'ATPCO Governing Rule Tariff Code.',
  `GRTARIFFNUM` varchar(3) DEFAULT NULL COMMENT 'Corresponding ATPCO Tariff Number.',
  `FF1AST` char(1) DEFAULT NULL COMMENT 'is not contained within PAPER TARIFF\r\n            (in LOC 56-62) but is coded to establish cross\r\n            relationships between tariffs.\r\n            CD: ATPCO Fare/Footnote Tariff Code.',
  `FF1TARIFFCD` varchar(8) DEFAULT NULL COMMENT 'ATPCO Fare/Footnote Tariff Code.',
  `FF1TARIFFNUM` varchar(3) DEFAULT NULL COMMENT 'Corresponding ATPCO Tariff Number.',
  `AFZ1AST` char(1) DEFAULT NULL COMMENT 'Symbol indicating that the tariff that\r\n            follows is not contained within PAPER TARIFF\r\n            (in LOC 56-62) but is coded to establish cross\r\n            relationships between tariffs.',
  `AFZ1TARIFFCD` varchar(8) DEFAULT NULL COMMENT 'ATPCO Arbitrary/Footnote/ Zone Tariff\r\n            Code.',
  `AFZ1TARIFFNUM` varchar(3) DEFAULT NULL COMMENT 'Corresponding ATPCO Tariff Number.',
  `FF2AST` char(1) DEFAULT NULL COMMENT 'Symbol indicating that the tariff that\r\n            follows is not contained within PAPER TARIFF\r\n            (in LOC 56-62) but is coded to establish cross\r\n            relationships between tariffs.',
  `FF2TARIFFCD` varchar(8) DEFAULT NULL COMMENT 'ATPCO Fare/Footnote Tariff Code.',
  `FF2TARIFFNUM` varchar(3) DEFAULT NULL COMMENT 'Corresponding ATPCO Tariff Number.',
  `AFZ2AST` char(1) DEFAULT NULL COMMENT 'Symbol indicating that the tariff that\r\n            follows is not contained within PAPER TARIFF\r\n            (in LOC 56-62) but is coded to establish cross\r\n            relationships between tariffs.',
  `AFZ2TARIFFCD` varchar(8) DEFAULT NULL COMMENT 'ATPCO Arbitrary/Footnote/ Zone Tariff\r\n            Code.',
  `AFZ2TARIFFNUM` varchar(3) DEFAULT NULL COMMENT 'Corresponding ATPCO Tariff Number.',
  `FF3AST` char(1) DEFAULT NULL COMMENT 'Symbol indicating that the tariff that\r\n            follows is not contained within PAPER TARIFF\r\n            (in LOC 56-62) but is coded to establish cross\r\n            relationships between tariffs.',
  `FF3TARIFFCD` varchar(8) DEFAULT NULL COMMENT 'ATPCO Fare/Footnote Tariff Code.',
  `FF3TARIFFNUM` varchar(3) DEFAULT NULL COMMENT 'Corresponding ATPCO Tariff Number.',
  `AFZ3AST` char(1) DEFAULT NULL COMMENT 'Symbol indicating that the tariff that\r\n            follows is not contained within PAPER TARIFF\r\n            (in LOC 56-62) but is coded to establish cross\r\n            relationships between tariffs.',
  `AFZ3TARIFFCD` varchar(8) DEFAULT NULL COMMENT 'ATPCO Arbitrary/Footnote/ Zone Tariff\r\n            Code.',
  `AFZ3TARIFFNUM` varchar(3) DEFAULT NULL COMMENT 'Corresponding ATPCO Tariff',
  `FF4AST` char(1) DEFAULT NULL COMMENT 'Symbol indicating that the tariff that\r\n            follows is not contained within PAPER TARIFF\r\n            (in LOC 56-62) but is coded to establish cross\r\n            relationships between tariffs.',
  `FF4TARIFFCD` varchar(8) DEFAULT NULL COMMENT 'ATPCO Fare/Footnote Tariff Code.',
  `FF4TARIFFNUM` varchar(3) DEFAULT NULL COMMENT 'Corresponding ATPCO Tariff Number',
  `AFZ4AST` char(1) DEFAULT NULL COMMENT 'Symbol indicating that the tariff that\r\n            follows is not contained within PAPER TARIFF\r\n            (in LOC 56-62) but is coded to establish cross\r\n            relationships between tariffs.',
  `AFZ4TARIFFCD` varchar(8) DEFAULT NULL COMMENT 'ATPCO Arbitrary/Footnote/ Zone Tariff\r\n            Code.',
  `AFZ4TARIFFNUM` varchar(3) DEFAULT NULL COMMENT 'Corresponding ATPCO Tariff Number.',
  `FILLER2` varchar(16) DEFAULT NULL COMMENT 'Filler',
  `UNPUBAST` char(1) DEFAULT NULL COMMENT 'Symbol indicating that the tariff that\r\n            follows is not contained within PAPER TARIFF\r\n            (in LOC 56-62) but is coded to establish cross\r\n            relationships between tariffs.',
  `UNPUBTARIFFCD` varchar(8) DEFAULT NULL COMMENT 'ATPCO Unpublished Tariff Code.',
  `UNPUBTARIFFNUM` varchar(3) DEFAULT NULL COMMENT 'Corresponding ATPCO Tariff Number.',
  `RTG1AST` char(1) DEFAULT NULL COMMENT 'Symbol indicating that the tariff that\r\n            follows is not contained within PAPER TARIFF\r\n            (in LOC 56-62) but is coded to establish cross\r\n            relationships between tariffs.',
  `RTG1TARIFFCD` varchar(8) DEFAULT NULL COMMENT 'ATPCO Routing Tariff Code.',
  `RTG1TARIFFNUM` varchar(3) DEFAULT NULL COMMENT 'Corresponding ATPCO Tariff Number.',
  `AREACODE1` varchar(2) DEFAULT NULL COMMENT 'ATPCO Area Code 1 indicating another\r\n            area in which the PAPER TARIFF (in LOC 56-\r\n            62) may be found.',
  `AREACODE3` varchar(2) DEFAULT NULL COMMENT 'ATPCO Area Code 2 indicating another\r\n            area in which the PAPER TARIFF (in LOC 56-\r\n            62) may be found.',
  `AREACODE2` varchar(2) DEFAULT NULL COMMENT 'ATPCO Area Code 3 indicating another\r\n            area in which the PAPER TARIFF (in LOC 56-\r\n            62) may be found.',
  `AREACODE4` varchar(2) DEFAULT NULL COMMENT 'ATPCO Area Code 4 indicating another\r\n            area in which the PAPER TARIFF (in LOC 56-\r\n            62) may be found.',
  `RTG2AST` char(1) DEFAULT NULL COMMENT 'Symbol indicating that the tariff that\r\n            follows is not contained within PAPER TARIFF\r\n            (in LOC 56-62) but is coded to establish cross\r\n            relationships between tariffs.',
  `RTG2TARIFFCD` varchar(8) DEFAULT NULL COMMENT 'ATPCO Routing Tariff Code.',
  `RTG2TARIFFNUM` varchar(3) DEFAULT NULL COMMENT 'Corresponding ATPCO Tariff Number.',
  `FILLER3` varchar(32) DEFAULT NULL,
  `FILLER4` varchar(10) DEFAULT NULL COMMENT 'Filler',
  `CreateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UpdateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '变更时间',
  PRIMARY KEY (`ID`)
) ;

